// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfhgxzjacnhwuzqpuqdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmaGd4emphY25od3V6cXB1cWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTkzODYsImV4cCI6MjA3MTg5NTM4Nn0.-w0JmD6JnhPxACmQFVFqCyZ3-uOtgYIj37BexGKiRWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});